# Generated by Django 2.2.12 on 2021-05-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedesigner',
            name='is_designer',
            field=models.BooleanField(default=True, verbose_name='Designer or Not'),
        ),
        migrations.AlterField(
            model_name='coursedesigner',
            name='is_lecturer',
            field=models.BooleanField(default=True, verbose_name='Lecturer or Not'),
        ),
        migrations.AlterField(
            model_name='noncoursedesigner',
            name='is_lecturer',
            field=models.BooleanField(default=True, verbose_name='Lecturer or Not'),
        ),
    ]
