# Generated by Django 2.2.12 on 2021-05-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210520_0153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
