# Generated by Django 2.2.12 on 2021-05-22 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedesigner',
            name='is_designer',
        ),
        migrations.RemoveField(
            model_name='coursedesigner',
            name='is_lecturer',
        ),
        migrations.RemoveField(
            model_name='noncoursedesigner',
            name='is_designer',
        ),
        migrations.RemoveField(
            model_name='noncoursedesigner',
            name='is_lecturer',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_lecturer',
        ),
    ]
