# Generated by Django 2.2.12 on 2021-05-24 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False, verbose_name='Course ID')),
                ('CourseName', models.CharField(default='', max_length=25, verbose_name='Course Name')),
                ('Code', models.CharField(default='', max_length=10, verbose_name='Course Code')),
                ('Type', models.CharField(default='', max_length=10, verbose_name='Course Type')),
                ('Program', models.CharField(default='', max_length=10, verbose_name='Course Program')),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='CILO',
            fields=[
                ('CILOID', models.AutoField(primary_key=True, serialize=False, verbose_name='CILO ID')),
                ('CILOName', models.CharField(default='', max_length=25, verbose_name='CILO Name')),
                ('Description', models.TextField(default='', verbose_name='CILO Description')),
                ('PreCILO', models.CharField(default='', max_length=25, verbose_name='Previous CILO')),
                ('AcademicYear', models.IntegerField(default=2005, verbose_name='Academic Year')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'db_table': 'CILO',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('AssessmentID', models.AutoField(primary_key=True, serialize=False, verbose_name='Assessment ID')),
                ('MethodName', models.CharField(default='', max_length=25, verbose_name='Method Name')),
                ('Percentage', models.FloatField(default=0.0, verbose_name='Percentage')),
                ('CILOIDs', models.CharField(default='', max_length=25, verbose_name='CILOIDs')),
                ('AcademicYear', models.IntegerField(default=2005, verbose_name='Academic Year')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'db_table': 'Assessment',
            },
        ),
    ]
