# Generated by Django 2.2.12 on 2021-05-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_assessment_cilo_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cilo',
            name='PreCILO',
            field=models.CharField(default='', max_length=100, verbose_name='Previous CILO'),
        ),
    ]
